BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS plantaciones CASCADE;
DROP TABLE IF EXISTS plantas CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS plantas (
    id VARCHAR(40) PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL,
    especie VARCHAR(100) NOT NULL,
    kc_ini DOUBLE PRECISION NOT NULL,
    kc_mid DOUBLE PRECISION NOT NULL,
    kc_end DOUBLE PRECISION NOT NULL,
    raiz_m DOUBLE PRECISION NOT NULL,
    agotamiento DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS plantaciones (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    planta VARCHAR(40) NOT NULL REFERENCES plantas(id),
    ubicacion VARCHAR(160) NOT NULL,
    latitud DOUBLE PRECISION NOT NULL,
    longitud DOUBLE PRECISION NOT NULL,
    tipo_tierra VARCHAR(20) NOT NULL,
    etapa VARCHAR(20) NOT NULL,
    ultimo_riego TIMESTAMP WITH TIME ZONE,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMIT;